name: Build and test

on:
 workflow_dispatch:
 push:
    branches:
      - main
      - dev
 pull_request:
    branches:
      - main
      - dev

jobs:
 build-normal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm i

    - name: Build SvelteKit app
      run: pnpm run build

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
      
    - name: Run Playwright tests
      run: pnpm exec playwright test
      
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

 build-node:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm i

    - name: Replace adapter
      run: sed -i 's/adapter-auto/adapter-node/g' svelte.config.js

    - name: Build SvelteKit app
      run: pnpm run build
